### ISSUE TITLE
[SBBF] Won't Rebuild Assets...

### ISSUE THREAD

**Issue by crystalman132** [wizzomafizzo/starcheat#126]
every time i launch starcheat, (upbeat giraffe) i get this, http://i.imgur.com/8ZmO6zZ.png , then i get this error message (it crashes) when i press yes/no. 

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 67, in __init__
  File "build\gui\utils.py", line 95, in check_index_valid
  File "build\gui\utils.py", line 57, in build_assets_db
  File "build\assets.py", line 227, in find_assets
  File "build\assets.py", line 233, in scan_modpak
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by wizzomafizzo** [comment]
can you try again but with a brand new cloned repo instead of an old one and see if that works (assuming you built it yourself)

**Comment by crystalman132** [comment]
built what myself?

**Comment by crystalman132** [comment]
i just installed starcheat and tried to run it. :I

**Comment by archfiendrubicante** [comment]
He's referring to the process by which Python files build from the build.py file to generate an executable.

**Comment by crystalman132** [comment]
... i just know how to mod items... i am pretty confused now. :I

**Comment by archfiendrubicante** [comment]
Mmm.. The best way to describe it is legos.
Each individual piece of python code has certain dependencies, aka different kinds of legos
Once you have those individual pieces of code you can use them along with instructions ( build.py ) in order to create a working executable piece of code (starcheat.exe)

**Comment by crystalman132** [comment]
so, do i need build.py? cuz i don't see it

anywhere

**Comment by archfiendrubicante** [comment]
Err.. No. I was just explaining the process of building executable files to you. My recommendation would be to remove any current versions of starcheat you have installed, download a fresh version of the latest stable zip for Giraffe, and then after shutting down all servers, and instances of starbound, boot the exe, designate your starbound folder, and then let the assets load from there.

**Comment by crystalman132** [comment]
i already dele- oh

**Comment by archfiendrubicante** [comment]
Most programs have issues loading information if a file is being used by another program. If you close out those programs and then reload the process it normally fixes a few problems.

Please tell us if this fixed your issue so we can change the status to closed if it did.

**Comment by crystalman132** [comment]
didn't work...

**Comment by wizzomafizzo** [comment]
@crystalman132  hi. sorry, i thought you had built it yourself from scratch. don't worry about it in that case

are you using any mods? if so i think i know what might be causing this

**Comment by Reedfish** [comment]
getting the same issue aswell, seems to have been the mods though.

**Comment by chrmoritz** [comment]
I think the issues was caused by starcheat reading old mods in the old mods location instead of the new one in `giraffe_storage`. Should be fixed in dbf1682 now (Refs #136).

**Comment by chrmoritz** [comment]
Binaries for this are now up at https://github.com/chrmoritz/starcheat/releases/tag/0.18.2 for testing.

**Comment by Shy-lo** [comment]
Hi, sorry. A bit new to this, but I've been messing around on the github trying to get this to work for about an hour now. I don't really know python at all, so I don't know how much help I can be.

So I've tried the new binaries. I still get the exact same error code as the opening post:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 61, in __init__
  File "build\gui\utils.py", line 184, in new_setup_dialog
  File "build\gui\utils.py", line 57, in build_assets_db
  File "build\assets.py", line 215, in find_assets
  File "build\assets.py", line 242, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format


So... I guess just to say, the new binary doesn't work for me. Something odd I've noticed -- my python installation is NOT on my C:/ drive. It's on my F:/ drive, and is named just Python34, not Python34-x64.

That might be totally unrelated, but I thought it was odd so I might as well mention it.

**Comment by chrmoritz** [comment]
you have to remove the mods not updated for upbeat_giraffe yet from your mods folder

**Comment by Shy-lo** [comment]
See, I tried that. i tried even deleting the enitre mods folder. Same error :/

**Comment by chrmoritz** [comment]
the mods folder in `giraffe_storage`?

**Comment by Viomi** [comment]
Bump. Had a lot of mods, went through and removed them one by one to find the culprit.

Culprit was "Skyrail Sit Mod", from http://community.playstarbound.com/index.php?resources/skyrail-sits.2172/

Error message was

<code>Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 67, in __init__
  File "build\gui\utils.py", line 95, in check_index_valid
  File "build\gui\utils.py", line 57, in build_assets_db
  File "build\assets.py", line 228, in find_assets
  File "build\assets.py", line 234, in scan_modpak
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format
</code>

**Comment by chrmoritz** [comment]
Everyone having issues with mods in the old sbbf02 format should try out [version 0.19.1](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19.1) which should fix your issues.
